const productsBySize = {
  S: [
    { name: "ProductItem1" },
    { name: "ProductItem2" },
    { name: "ProductItem3" },
    { name: "ProductItem4" },
    { name: "ProductItem5" },
    { name: "ProductItem6" },
    { name: "ProductItem7" },
    { name: "ProductItem8" },
    { name: "ProductItem9" },
    { name: "ProductItem10" },
    { name: "ProductItem11" },
    { name: "ProductItem12" },
  ],
  XS: [
    { name: "ProductItem1" },
    { name: "ProductItem3" },
    { name: "ProductItem5" },
    { name: "ProductItem7" },
    { name: "ProductItem8" },
    { name: "ProductItem9" },
    { name: "ProductItem10" },
    { name: "ProductItem11" },
    { name: "ProductItem12" },
  ],
  L: [
    { name: "ProductItem1" },
    { name: "ProductItem2" },
    { name: "ProductItem5" },
    { name: "ProductItem7" },
    { name: "ProductItem10" },
    { name: "ProductItem11" },
  ],
  M: [{ name: "ProductItem1" }, { name: "ProductItem7" }],
};
